import type { Member, Settlement } from "./types";

export const sampleMembers: Member[] = [
  {
    id: "member-sato",
    name: "佐藤",
    preferredMethod: "paypay",
    paypayPhone: "09012345678",
    bankName: "",
    branchName: "",
    accountType: "",
    accountNumber: "",
    accountHolder: "",
    note: "PayPay優先",
  },
  {
    id: "member-tanaka",
    name: "田中",
    preferredMethod: "bank",
    paypayPhone: "",
    bankName: "みずほ銀行",
    branchName: "新宿支店",
    accountType: "普通",
    accountNumber: "1234567",
    accountHolder: "タナカハナコ",
    note: "平日は振込確認しやすい",
  },
  {
    id: "member-suzuki",
    name: "鈴木",
    preferredMethod: "paypay",
    paypayPhone: "08098765432",
    bankName: "三井住友銀行",
    branchName: "渋谷支店",
    accountType: "普通",
    accountNumber: "7654321",
    accountHolder: "スズキイチロウ",
    note: "どちらでも受け取り可能",
  },
  {
    id: "member-yamada",
    name: "山田",
    preferredMethod: "other",
    paypayPhone: "",
    bankName: "",
    branchName: "",
    accountType: "",
    accountNumber: "",
    accountHolder: "",
    note: "送金先未設定",
  },
];

export const sampleSettlements: Settlement[] = [
  {
    id: "settlement-1",
    fromMemberId: "member-yamada",
    toMemberId: "member-sato",
    amount: 3200,
    currency: "JPY",
    note: "飲み会",
  },
  {
    id: "settlement-2",
    fromMemberId: "member-suzuki",
    toMemberId: "member-tanaka",
    amount: 5000,
    currency: "JPY",
    note: "旅行立替",
  },
  {
    id: "settlement-3",
    fromMemberId: "member-sato",
    toMemberId: "member-yamada",
    amount: 1800,
    currency: "JPY",
    note: "タクシー代",
  },
];
